def is_header(text):
    t_clean = text.strip()
    if len(t_clean) < 4 or any(c.isdigit() for c in t_clean):
        return None
    
    t_up = t_clean.upper().replace('\n', ' ').strip()
    
    # 1. Manual aliases
    if "LIMITED EDITION" in t_up and "SANITARY" in t_up: return "LIMITED EDITION SANITARY WARE IN SPECIAL FINISHES"
    if "FLUSH TANKS" in t_up and "URINAL" in t_up: return "FLUSH TANKS/PLATES & URINAL SENSORS IN SPECIAL FINISHES"
    if "INTELLIGENT SMART TOILET" in t_up: return "INTELLIGENT SMART TOILET AQUANEXX SERIES"
    if "FAUCETS IN CHROME FINISH" in t_up: return "FAUCETS IN CHROME FINISH"
    if "CARE INSTRUCTIONS" in t_up: return "CARE INSTRUCTIONS"

    DASHBOARD_CATS = [
        "STONE WASH BASINS",
        "ARTISTIC WASH BASINS IN UNIQUE MATERIALS",
        "CERAMIC PEDESTAL WASH BASINS",
        "CERAMIC BASINS IN WHITE & SPECIAL FINISHES",
        "CERAMIC SANITARY WARE IN SPECIAL FINISHES",
        "LIMITED EDITION SANITARY WARE IN SPECIAL FINISHES",
        "CERAMIC BASINS IN SPECIAL FINISHES",
        "CERAMIC WASH BASINS",
        "INTELLIGENT SMART TOILET AQUANEXX SERIES",
        "TOILETS",
        "FLUSH TANKS/PLATES & URINAL SENSORS IN SPECIAL FINISHES",
        "PRESTIGE COLLECTION BASIN MIXERS",
        "FAUCETS & SHOWERING SYSTEMS IN SPECIAL FINISHES",
        "FAUCETS & SPOUTS IN SPECIAL FINISHES",
        "SHOWERING SYSTEMS IN SPECIAL FINISHES",
        "BODY JETS & BODY SHOWERS IN SPECIAL FINISHES",
        "HAND SHOWERS IN SPECIAL FINISHES",
        "BATH FITTINGS IN SPECIAL FINISHES",
        "FAUCETS IN SPECIAL FINISHES",
        "ALLIED PRODUCTS IN SPECIAL FINISHES",
        "ACCESSORIES IN SPECIAL FINISHES",
        "FAUCETS & SHOWERING SYSTEMS IN CHROME FINISH",
        "FAUCETS IN CHROME FINISH",
        "DIVERTERS & SHOWERING SYSTEMS IN CHROME & SPECIAL FINISH",
        "CONCEALED CEILING MOUNTED SHOWERS IN CHROME FINISH",
        "SHOWERS IN CHROME FINISH",
        "BODY JETS & BODY SHOWERS IN CHROME FINISH",
        "HAND SHOWERS & HEAD SHOWERS IN CHROME FINISH",
        "ALLIED PRODUCTS IN CHROME FINISH",
        "SS SHOWER PANELS IN MATT FINISH",
        "KITCHEN FAUCETS IN SPECIAL & CHROME FINISH",
        "FLOOR DRAINS IN CHROME & SPECIAL FINISHES",
        "BATH COMPONENTS",
        "OUR PROMISE",
        "CARE INSTRUCTIONS"
    ]

    best_match = None
    best_len = 0
    for dc in DASHBOARD_CATS:
        if dc in t_up:
            if len(dc) > best_len:
                best_len = len(dc)
                best_match = dc
    
    return best_match

print(is_header("LIMITED EDITION CERAMIC SANITARY WARE IN SPECIAL FINISHES"))
print(is_header("INTELLIGENT SMART TOILETS                    SERIES"))
print(is_header("FLUSH TANKS, FLUSH PLATES & URINAL SENSORS IN SPECIAL FINISHES"))
print(is_header("CARE INSTRUCTIONS"))
print(is_header("FAUCETS IN CHROME FINISH"))

